name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: capstone-project-mubazirapp
  GAR_LOCATION: gcr.io/capstone-project-mubazirapp/capstone/mubazir05
  SERVICE: ci
  REGION: asia-southeast2

jobs:
  build_and_deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SATRIO }}'

  push_docker:
    steps:
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gcr.io/capstone-project-mubazirapp/capstone/mubazir05
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SATRIO }}
        
      - name: Configure Docker to use GCR
        run: |
          echo ${{ secrets.SATRIO }} > gcr-key.json
          gcloud auth activate-service-account --key-file=gcr-key.json
          gcloud auth configure-docker gcr.io

      - name: Tag and Push to GCR
        run: |
          IMAGE_TAG=gcr.io/capstone-project-mubazirapp/capstone/mubazir05
          docker tag gcr.io/capstone-project-mubazirapp/capstone/mubazir05 $IMAGE_TAG
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.GAR_LOCATION }} \
            --quiet --platform managed --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }} --format json

      # If required, use the Cloud Run URL output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
