name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: capstone-project-mubazirapp
  IMAGE_NAME: gcr.io/capstone-project-mubazirapp/capstone/mubazir05
  SERVICE: ci
  REGION: asia-southeast2

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1 
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.SATRIO }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.SATRIO }}
          export_default_credentials: true

      - name: Get Secret from Secret Manager
        id: secret
        run: |
          SECRET_VALUE=$(gcloud secrets versions access latest --secret="env")
          echo "::set-output name=SECRET_VALUE::$SECRET_VALUE"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          build-args: |
            VAR1=${{ steps.secret.outputs.SECRET_VALUE }}
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
